// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Endpoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Rule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RuleAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserVPCAuthorization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Zone) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ZoneAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ZoneRecord) Hub() {}
