// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type UserVPCAuthorizationInitParameters struct {

	// The auth channel. Valid values: RESOURCE_DIRECTORY.
	AuthChannel *string `json:"authChannel,omitempty" tf:"auth_channel,omitempty"`

	// The type of Authorization. Valid values: NORMAL and CLOUD_PRODUCT.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// The primary account ID of the user who authorizes the resource.
	AuthorizedUserID *string `json:"authorizedUserId,omitempty" tf:"authorized_user_id,omitempty"`
}

type UserVPCAuthorizationObservation struct {

	// The auth channel. Valid values: RESOURCE_DIRECTORY.
	AuthChannel *string `json:"authChannel,omitempty" tf:"auth_channel,omitempty"`

	// The type of Authorization. Valid values: NORMAL and CLOUD_PRODUCT.
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// The primary account ID of the user who authorizes the resource.
	AuthorizedUserID *string `json:"authorizedUserId,omitempty" tf:"authorized_user_id,omitempty"`

	// The resource ID of User Vpc Authorization. The value formats as <authorized_user_id>:<auth_type>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type UserVPCAuthorizationParameters struct {

	// The auth channel. Valid values: RESOURCE_DIRECTORY.
	// +kubebuilder:validation:Optional
	AuthChannel *string `json:"authChannel,omitempty" tf:"auth_channel,omitempty"`

	// The type of Authorization. Valid values: NORMAL and CLOUD_PRODUCT.
	// +kubebuilder:validation:Optional
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// The primary account ID of the user who authorizes the resource.
	// +kubebuilder:validation:Optional
	AuthorizedUserID *string `json:"authorizedUserId,omitempty" tf:"authorized_user_id,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`
}

// UserVPCAuthorizationSpec defines the desired state of UserVPCAuthorization
type UserVPCAuthorizationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserVPCAuthorizationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserVPCAuthorizationInitParameters `json:"initProvider,omitempty"`
}

// UserVPCAuthorizationStatus defines the observed state of UserVPCAuthorization.
type UserVPCAuthorizationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserVPCAuthorizationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserVPCAuthorization is the Schema for the UserVPCAuthorizations API. Provides a Alicloud Private Zone User Vpc Authorization resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type UserVPCAuthorization struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authorizedUserId) || (has(self.initProvider) && has(self.initProvider.authorizedUserId))",message="spec.forProvider.authorizedUserId is a required parameter"
	Spec   UserVPCAuthorizationSpec   `json:"spec"`
	Status UserVPCAuthorizationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserVPCAuthorizationList contains a list of UserVPCAuthorizations
type UserVPCAuthorizationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserVPCAuthorization `json:"items"`
}

// Repository type metadata.
var (
	UserVPCAuthorization_Kind             = "UserVPCAuthorization"
	UserVPCAuthorization_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserVPCAuthorization_Kind}.String()
	UserVPCAuthorization_KindAPIVersion   = UserVPCAuthorization_Kind + "." + CRDGroupVersion.String()
	UserVPCAuthorization_GroupVersionKind = CRDGroupVersion.WithKind(UserVPCAuthorization_Kind)
)

func init() {
	SchemeBuilder.Register(&UserVPCAuthorization{}, &UserVPCAuthorizationList{})
}
