apiVersion: snat.alibabacloud.crossplane.io/v1alpha1
kind: Entry
metadata:
  annotations:
    meta.upbound.io/example-id: snat/v1alpha1/entry
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: cn-beijing
    snatIpSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    snatTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    sourceVswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: eip.alibabacloud.crossplane.io/v1alpha1
kind: Address
metadata:
  annotations:
    meta.upbound.io/example-id: snat/v1alpha1/entry
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    addressName: ${var.name}
    region: cn-beijing

---

apiVersion: eip.alibabacloud.crossplane.io/v1alpha1
kind: Association
metadata:
  annotations:
    meta.upbound.io/example-id: snat/v1alpha1/entry
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    allocationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    region: cn-beijing

---

apiVersion: nat.alibabacloud.crossplane.io/v1alpha1
kind: Gateway
metadata:
  annotations:
    meta.upbound.io/example-id: snat/v1alpha1/entry
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    natGatewayName: ${var.name}
    natType: Enhanced
    paymentType: PayAsYouGo
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: snat/v1alpha1/entry
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.16.0.0/12
    region: cn-beijing
    vpcName: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: snat/v1alpha1/entry
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.16.0.0/21
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchName: ${var.name}
    zoneId: ${data.alicloud_zones.default.zones.0.id}
