// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AclEntryAttachment.
func (mg *AclEntryAttachment) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ACLID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ACLIDRef,
		Selector:     mg.Spec.ForProvider.ACLIDSelector,
		To: reference.To{
			List:    &AclList{},
			Managed: &Acl{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ACLID")
	}
	mg.Spec.ForProvider.ACLID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ACLIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ACLID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ACLIDRef,
		Selector:     mg.Spec.InitProvider.ACLIDSelector,
		To: reference.To{
			List:    &AclList{},
			Managed: &Acl{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ACLID")
	}
	mg.Spec.InitProvider.ACLID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ACLIDRef = rsp.ResolvedReference

	return nil
}
