apiVersion: fcv3.alibabacloud.crossplane.io/v1alpha1
kind: AsyncInvokeConfig
metadata:
  annotations:
    meta.upbound.io/example-id: fcv3/v1alpha1/asyncinvokeconfig
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    asyncTask: "true"
    destinationConfig:
    - onFailure:
      - destinationSelector:
          matchLabels:
            testing.upbound.io/example-name: alicloud_account
      onSuccess:
      - destinationSelector:
          matchLabels:
            testing.upbound.io/example-name: alicloud_account
    functionNameSelector:
      matchLabels:
        testing.upbound.io/example-name: function
    maxAsyncEventAgeInSeconds: "1"
    maxAsyncRetryAttempts: "1"
    qualifier: LATEST
    region: cn-beijing

---

apiVersion: fcv3.alibabacloud.crossplane.io/v1alpha1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: fcv3/v1alpha1/asyncinvokeconfig
  labels:
    testing.upbound.io/example-name: function
  name: function
spec:
  forProvider:
    code:
    - zipFile: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAaW5kZXgucHmEkEFKxEAQRfd9ig9ZTCJOooIwDMwNXLqXnnQlaalUhU5lRj2KZ/FOXkESGR114bJ/P/7jV4b1xRq1hijtFpM1682cuNgPmgysbRulPT0fRxXnMtwrSPyeCdYRokSLnuMLJTTkbUqEvDMbxm1VdcRD6Tk+T1LW2ldB66knsYdA5iNX17ebm6tN2VnPhcswMPmREPuBacb+CiapLarAj9gT6/H97dVlCNScY3mtYvRkxdZlwDKDEnanPWVLdrdkeXEGlFEazVdfPVHaVeHc3N15CUwppwOJXeK7HshAB8NuOU7J6sP4SRXuH/EvbUfMiqMmDqv5M5FNSfAj/wgAAP//UEsHCPl//NYAAQAArwEAAFBLAQIUABQACAAIAAAAAAD5f/zWAAEAAK8BAAAIAAAAAAAAAAAAAAAAAAAAAABpbmRleC5weVBLBQYAAAAAAQABADYAAAA2AQAAAAA=
    cpu: 0.5
    diskSize: "512"
    functionName: ${var.name}
    handler: index.Handler
    logConfig:
    - logBeginRule: None
    memorySize: "512"
    region: cn-beijing
    runtime: python3.9

---

apiVersion: fcv3.alibabacloud.crossplane.io/v1alpha1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: fcv3/v1alpha1/asyncinvokeconfig
  labels:
    testing.upbound.io/example-name: function1
  name: function1
spec:
  forProvider:
    code:
    - zipFile: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAaW5kZXgucHmEkEFKxEAQRfd9ig9ZTCJOooIwDMwNXLqXnnQlaalUhU5lRj2KZ/FOXkESGR114bJ/P/7jV4b1xRq1hijtFpM1682cuNgPmgysbRulPT0fRxXnMtwrSPyeCdYRokSLnuMLJTTkbUqEvDMbxm1VdcRD6Tk+T1LW2ldB66knsYdA5iNX17ebm6tN2VnPhcswMPmREPuBacb+CiapLarAj9gT6/H97dVlCNScY3mtYvRkxdZlwDKDEnanPWVLdrdkeXEGlFEazVdfPVHaVeHc3N15CUwppwOJXeK7HshAB8NuOU7J6sP4SRXuH/EvbUfMiqMmDqv5M5FNSfAj/wgAAP//UEsHCPl//NYAAQAArwEAAFBLAQIUABQACAAIAAAAAAD5f/zWAAEAAK8BAAAIAAAAAAAAAAAAAAAAAAAAAABpbmRleC5weVBLBQYAAAAAAQABADYAAAA2AQAAAAA=
    cpu: 0.5
    diskSize: "512"
    functionName: ${format("%s_%s", var.name, "update1")}
    handler: index.Handler
    logConfig:
    - logBeginRule: None
    memorySize: "512"
    region: cn-beijing
    runtime: python3.9

---

apiVersion: fcv3.alibabacloud.crossplane.io/v1alpha1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: fcv3/v1alpha1/asyncinvokeconfig
  labels:
    testing.upbound.io/example-name: function2
  name: function2
spec:
  forProvider:
    code:
    - zipFile: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAaW5kZXgucHmEkEFKxEAQRfd9ig9ZTCJOooIwDMwNXLqXnnQlaalUhU5lRj2KZ/FOXkESGR114bJ/P/7jV4b1xRq1hijtFpM1682cuNgPmgysbRulPT0fRxXnMtwrSPyeCdYRokSLnuMLJTTkbUqEvDMbxm1VdcRD6Tk+T1LW2ldB66knsYdA5iNX17ebm6tN2VnPhcswMPmREPuBacb+CiapLarAj9gT6/H97dVlCNScY3mtYvRkxdZlwDKDEnanPWVLdrdkeXEGlFEazVdfPVHaVeHc3N15CUwppwOJXeK7HshAB8NuOU7J6sP4SRXuH/EvbUfMiqMmDqv5M5FNSfAj/wgAAP//UEsHCPl//NYAAQAArwEAAFBLAQIUABQACAAIAAAAAAD5f/zWAAEAAK8BAAAIAAAAAAAAAAAAAAAAAAAAAABpbmRleC5weVBLBQYAAAAAAQABADYAAAA2AQAAAAA=
    cpu: 0.5
    diskSize: "512"
    functionName: ${format("%s_%s", var.name, "update2")}
    handler: index.Handler
    logConfig:
    - logBeginRule: None
    memorySize: "512"
    region: cn-beijing
    runtime: python3.9
