apiVersion: alibabacloud.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: sts-token
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-sts-creds
      namespace: crossplane-system
      key: credentials
