apiVersion: alibabacloud.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: assume-role-with-oidc
spec:
  credentials:
    source: None
  assumeRoleWithOIDC:
    roleARN: acs:ram::<account-id>:role/<role-name>
    oidcProviderARN: acs:ram::<account-id>:oidc-provider/<provider-name>
    oidcTokenFile: /var/run/secrets/ack.alibabacloud.com/rrsa-tokens/token
    roleSessionName: crossplane-oidc
    sessionExpiration: 3600
