apiVersion: alibabacloud.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: assume-role
spec:
  credentials:
    source: Secret
    secretRef:
      name: example-creds
      namespace: crossplane-system
      key: credentials
  assumeRole:
    roleARN: acs:ram::<account-id>:role/<role-name>
    sessionName: crossplane-assume-role
    sessionExpiration: 3600
