apiVersion: ack.alibabacloud.crossplane.io/v1alpha1
kind: Kubernetes
metadata:
  annotations:
    meta.upbound.io/example-id: ack/v1alpha1/kubernetes
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    clusterDomain: cluster.local
    customSan: www.terraform.io
    deletionProtection: false
    dynamic:
      addons:
      - content:
        - config: ${jsonencode(lookup(addons.value, "config", var.cluster_addons))}
          name: ${lookup(addons.value, "name", var.cluster_addons)}
        for_each: ${var.cluster_addons}
    installCloudMonitor: true
    masterDiskCategory: cloud_essd
    masterInstanceTypes:
    - ${data.alicloud_instance_types.cloud_essd.0.instance_types.0.id}
    - ${data.alicloud_instance_types.cloud_essd.1.instance_types.0.id}
    - ${data.alicloud_instance_types.cloud_essd.2.instance_types.0.id}
    masterVswitchIdsSelector:
      matchLabels:
        testing.upbound.io/example-name: vswitch_ids) > 0 ? split(",", join(",", var
    newNatGateway: true
    osType: Linux
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    platform: AliyunLinux3
    podVswitchIdsSelector:
      matchLabels:
        testing.upbound.io/example-name: terway_vswitch_ids) > 0 ? split(",", join(",",
          var
    proxyMode: ipvs
    region: cn-beijing
    resourceGroupId: ${data.alicloud_resource_manager_resource_groups.default.groups.0.id}
    serviceCidr: 172.18.0.0/16
    skipSetCertificateAuthority: true
    timezone: Asia/Shanghai

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ack/v1alpha1/kubernetes
  labels:
    testing.upbound.io/example-name: vpc
  name: vpc
spec:
  forProvider:
    cidrBlock: ${var.vpc_cidr}
    count: '${var.vpc_id == "" ? 1 : 0}'
    region: cn-beijing

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: ack/v1alpha1/kubernetes
  labels:
    testing.upbound.io/example-name: terway_vswitches
  name: terway-vswitches
spec:
  forProvider:
    cidrBlock: ${element(var.terway_vswitch_cidrs, count.index)}
    count: '${length(var.terway_vswitch_ids) > 0 ? 0 : length(var.terway_vswitch_cidrs)}'
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc_id == "" ? join("", alicloud_vpc
    zoneId: '${data.alicloud_enhanced_nat_available_zones.enhanced.zones[count.index
      < length(data.alicloud_enhanced_nat_available_zones.enhanced.zones) ? count.index
      : 0].zone_id}'

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: ack/v1alpha1/kubernetes
  labels:
    testing.upbound.io/example-name: vswitches
  name: vswitches
spec:
  forProvider:
    cidrBlock: ${element(var.vswitch_cidrs, count.index)}
    count: '${length(var.vswitch_ids) > 0 ? 0 : length(var.vswitch_cidrs)}'
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vpc_id == "" ? join("", alicloud_vpc
    zoneId: '${data.alicloud_enhanced_nat_available_zones.enhanced.zones[count.index
      < length(data.alicloud_enhanced_nat_available_zones.enhanced.zones) ? count.index
      : 0].zone_id}'
