// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ForwardEntryInitParameters struct {

	// - When querying DNAT entries of an Internet NAT gateway, this parameter indicates the Elastic IP address used in the DNAT entry to provide public network access.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/natgateway/v1alpha1.VPCNATIP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("nat_ip",false)
	ExternalIP *string `json:"externalIp,omitempty" tf:"external_ip,omitempty"`

	// Reference to a VPCNATIP in natgateway to populate externalIp.
	// +kubebuilder:validation:Optional
	ExternalIPRef *v1.Reference `json:"externalIpRef,omitempty" tf:"-"`

	// Selector for a VPCNATIP in natgateway to populate externalIp.
	// +kubebuilder:validation:Optional
	ExternalIPSelector *v1.Selector `json:"externalIpSelector,omitempty" tf:"-"`

	// - The external port or port range that is used for port forwarding when you query DNAT entries of Internet NAT gateways. Valid values: 1 to 65535.
	ExternalPort *string `json:"externalPort,omitempty" tf:"external_port,omitempty"`

	// The name of the DNAT entry.
	ForwardEntryName *string `json:"forwardEntryName,omitempty" tf:"forward_entry_name,omitempty"`

	// The ID of the DNAT table to which the DNAT entry belongs.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/natgateway/v1alpha1.NATGateway
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("forward_table_ids",true)
	ForwardTableID *string `json:"forwardTableId,omitempty" tf:"forward_table_id,omitempty"`

	// Reference to a NATGateway in natgateway to populate forwardTableId.
	// +kubebuilder:validation:Optional
	ForwardTableIDRef *v1.Reference `json:"forwardTableIdRef,omitempty" tf:"-"`

	// Selector for a NATGateway in natgateway to populate forwardTableId.
	// +kubebuilder:validation:Optional
	ForwardTableIDSelector *v1.Selector `json:"forwardTableIdSelector,omitempty" tf:"-"`

	// The protocol type. Valid values:
	IPProtocol *string `json:"ipProtocol,omitempty" tf:"ip_protocol,omitempty"`

	// - The private IP address.
	InternalIP *string `json:"internalIp,omitempty" tf:"internal_ip,omitempty"`

	// - When you configure a DNAT entry for an Internet NAT gateway, this parameter specifies the internal port or port range that requires port forwarding. Valid values: 1 to 65535.
	InternalPort *string `json:"internalPort,omitempty" tf:"internal_port,omitempty"`

	// Specifies whether to enable port break. Valid values:
	PortBreak *bool `json:"portBreak,omitempty" tf:"port_break,omitempty"`
}

type ForwardEntryObservation struct {

	// - When querying DNAT entries of an Internet NAT gateway, this parameter indicates the Elastic IP address used in the DNAT entry to provide public network access.
	ExternalIP *string `json:"externalIp,omitempty" tf:"external_ip,omitempty"`

	// - The external port or port range that is used for port forwarding when you query DNAT entries of Internet NAT gateways. Valid values: 1 to 65535.
	ExternalPort *string `json:"externalPort,omitempty" tf:"external_port,omitempty"`

	// (Available since v1.43.0) The id of the forward entry on the server.
	ForwardEntryID *string `json:"forwardEntryId,omitempty" tf:"forward_entry_id,omitempty"`

	// The name of the DNAT entry.
	ForwardEntryName *string `json:"forwardEntryName,omitempty" tf:"forward_entry_name,omitempty"`

	// The ID of the DNAT table to which the DNAT entry belongs.
	ForwardTableID *string `json:"forwardTableId,omitempty" tf:"forward_table_id,omitempty"`

	// The ID of the resource supplied above. The value is formulated as <forward_table_id>:<forward_entry_id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The protocol type. Valid values:
	IPProtocol *string `json:"ipProtocol,omitempty" tf:"ip_protocol,omitempty"`

	// - The private IP address.
	InternalIP *string `json:"internalIp,omitempty" tf:"internal_ip,omitempty"`

	// - When you configure a DNAT entry for an Internet NAT gateway, this parameter specifies the internal port or port range that requires port forwarding. Valid values: 1 to 65535.
	InternalPort *string `json:"internalPort,omitempty" tf:"internal_port,omitempty"`

	// Specifies whether to enable port break. Valid values:
	PortBreak *bool `json:"portBreak,omitempty" tf:"port_break,omitempty"`

	// (Available since v1.119.1) The status of forward entry.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type ForwardEntryParameters struct {

	// - When querying DNAT entries of an Internet NAT gateway, this parameter indicates the Elastic IP address used in the DNAT entry to provide public network access.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/natgateway/v1alpha1.VPCNATIP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("nat_ip",false)
	// +kubebuilder:validation:Optional
	ExternalIP *string `json:"externalIp,omitempty" tf:"external_ip,omitempty"`

	// Reference to a VPCNATIP in natgateway to populate externalIp.
	// +kubebuilder:validation:Optional
	ExternalIPRef *v1.Reference `json:"externalIpRef,omitempty" tf:"-"`

	// Selector for a VPCNATIP in natgateway to populate externalIp.
	// +kubebuilder:validation:Optional
	ExternalIPSelector *v1.Selector `json:"externalIpSelector,omitempty" tf:"-"`

	// - The external port or port range that is used for port forwarding when you query DNAT entries of Internet NAT gateways. Valid values: 1 to 65535.
	// +kubebuilder:validation:Optional
	ExternalPort *string `json:"externalPort,omitempty" tf:"external_port,omitempty"`

	// The name of the DNAT entry.
	// +kubebuilder:validation:Optional
	ForwardEntryName *string `json:"forwardEntryName,omitempty" tf:"forward_entry_name,omitempty"`

	// The ID of the DNAT table to which the DNAT entry belongs.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/natgateway/v1alpha1.NATGateway
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractParamPath("forward_table_ids",true)
	// +kubebuilder:validation:Optional
	ForwardTableID *string `json:"forwardTableId,omitempty" tf:"forward_table_id,omitempty"`

	// Reference to a NATGateway in natgateway to populate forwardTableId.
	// +kubebuilder:validation:Optional
	ForwardTableIDRef *v1.Reference `json:"forwardTableIdRef,omitempty" tf:"-"`

	// Selector for a NATGateway in natgateway to populate forwardTableId.
	// +kubebuilder:validation:Optional
	ForwardTableIDSelector *v1.Selector `json:"forwardTableIdSelector,omitempty" tf:"-"`

	// The protocol type. Valid values:
	// +kubebuilder:validation:Optional
	IPProtocol *string `json:"ipProtocol,omitempty" tf:"ip_protocol,omitempty"`

	// - The private IP address.
	// +kubebuilder:validation:Optional
	InternalIP *string `json:"internalIp,omitempty" tf:"internal_ip,omitempty"`

	// - When you configure a DNAT entry for an Internet NAT gateway, this parameter specifies the internal port or port range that requires port forwarding. Valid values: 1 to 65535.
	// +kubebuilder:validation:Optional
	InternalPort *string `json:"internalPort,omitempty" tf:"internal_port,omitempty"`

	// Specifies whether to enable port break. Valid values:
	// +kubebuilder:validation:Optional
	PortBreak *bool `json:"portBreak,omitempty" tf:"port_break,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`
}

// ForwardEntrySpec defines the desired state of ForwardEntry
type ForwardEntrySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ForwardEntryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ForwardEntryInitParameters `json:"initProvider,omitempty"`
}

// ForwardEntryStatus defines the observed state of ForwardEntry.
type ForwardEntryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ForwardEntryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ForwardEntry is the Schema for the ForwardEntrys API. Provides a Alicloud Nat Gateway Forward Entry resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type ForwardEntry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.externalPort) || (has(self.initProvider) && has(self.initProvider.externalPort))",message="spec.forProvider.externalPort is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.internalIp) || (has(self.initProvider) && has(self.initProvider.internalIp))",message="spec.forProvider.internalIp is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.internalPort) || (has(self.initProvider) && has(self.initProvider.internalPort))",message="spec.forProvider.internalPort is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ipProtocol) || (has(self.initProvider) && has(self.initProvider.ipProtocol))",message="spec.forProvider.ipProtocol is a required parameter"
	Spec   ForwardEntrySpec   `json:"spec"`
	Status ForwardEntryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ForwardEntryList contains a list of ForwardEntrys
type ForwardEntryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ForwardEntry `json:"items"`
}

// Repository type metadata.
var (
	ForwardEntry_Kind             = "ForwardEntry"
	ForwardEntry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ForwardEntry_Kind}.String()
	ForwardEntry_KindAPIVersion   = ForwardEntry_Kind + "." + CRDGroupVersion.String()
	ForwardEntry_GroupVersionKind = CRDGroupVersion.WithKind(ForwardEntry_Kind)
)

func init() {
	SchemeBuilder.Register(&ForwardEntry{}, &ForwardEntryList{})
}
