// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/eip/v1alpha1"
	v1alpha11 "github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/vpc/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	resource "github.com/crossplane/upjet/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ForwardEntry.
func (mg *ForwardEntry) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ExternalIP),
		Extract:      resource.ExtractParamPath("ip_address", false),
		Reference:    mg.Spec.ForProvider.ExternalIPRef,
		Selector:     mg.Spec.ForProvider.ExternalIPSelector,
		To: reference.To{
			List:    &v1alpha1.EIPAddressList{},
			Managed: &v1alpha1.EIPAddress{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ExternalIP")
	}
	mg.Spec.ForProvider.ExternalIP = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ExternalIPRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ForwardTableID),
		Extract:      resource.ExtractParamPath("forward_table_ids", true),
		Reference:    mg.Spec.ForProvider.ForwardTableIDRef,
		Selector:     mg.Spec.ForProvider.ForwardTableIDSelector,
		To: reference.To{
			List:    &NATGatewayList{},
			Managed: &NATGateway{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ForwardTableID")
	}
	mg.Spec.ForProvider.ForwardTableID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ForwardTableIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ExternalIP),
		Extract:      resource.ExtractParamPath("ip_address", false),
		Reference:    mg.Spec.InitProvider.ExternalIPRef,
		Selector:     mg.Spec.InitProvider.ExternalIPSelector,
		To: reference.To{
			List:    &v1alpha1.EIPAddressList{},
			Managed: &v1alpha1.EIPAddress{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ExternalIP")
	}
	mg.Spec.InitProvider.ExternalIP = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ExternalIPRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ForwardTableID),
		Extract:      resource.ExtractParamPath("forward_table_ids", true),
		Reference:    mg.Spec.InitProvider.ForwardTableIDRef,
		Selector:     mg.Spec.InitProvider.ForwardTableIDSelector,
		To: reference.To{
			List:    &NATGatewayList{},
			Managed: &NATGateway{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ForwardTableID")
	}
	mg.Spec.InitProvider.ForwardTableID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ForwardTableIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this NATGateway.
func (mg *NATGateway) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.VPCIDRef,
		Selector:     mg.Spec.ForProvider.VPCIDSelector,
		To: reference.To{
			List:    &v1alpha11.VPCList{},
			Managed: &v1alpha11.VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VPCID")
	}
	mg.Spec.ForProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VPCIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VswitchID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.VswitchIDRef,
		Selector:     mg.Spec.ForProvider.VswitchIDSelector,
		To: reference.To{
			List:    &v1alpha11.VswitchList{},
			Managed: &v1alpha11.Vswitch{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.VswitchID")
	}
	mg.Spec.ForProvider.VswitchID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VswitchIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.VPCIDRef,
		Selector:     mg.Spec.InitProvider.VPCIDSelector,
		To: reference.To{
			List:    &v1alpha11.VPCList{},
			Managed: &v1alpha11.VPC{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VPCID")
	}
	mg.Spec.InitProvider.VPCID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VPCIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VswitchID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.VswitchIDRef,
		Selector:     mg.Spec.InitProvider.VswitchIDSelector,
		To: reference.To{
			List:    &v1alpha11.VswitchList{},
			Managed: &v1alpha11.Vswitch{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.VswitchID")
	}
	mg.Spec.InitProvider.VswitchID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VswitchIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SNATEntry.
func (mg *SNATEntry) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SnatIP),
		Extract:      resource.ExtractParamPath("ip_address", false),
		Reference:    mg.Spec.ForProvider.SnatIPRef,
		Selector:     mg.Spec.ForProvider.SnatIPSelector,
		To: reference.To{
			List:    &v1alpha1.EIPAddressList{},
			Managed: &v1alpha1.EIPAddress{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SnatIP")
	}
	mg.Spec.ForProvider.SnatIP = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SnatIPRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SnatTableID),
		Extract:      resource.ExtractParamPath("snat_table_ids", true),
		Reference:    mg.Spec.ForProvider.SnatTableIDRef,
		Selector:     mg.Spec.ForProvider.SnatTableIDSelector,
		To: reference.To{
			List:    &NATGatewayList{},
			Managed: &NATGateway{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SnatTableID")
	}
	mg.Spec.ForProvider.SnatTableID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SnatTableIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceVswitchID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.SourceVswitchIDRef,
		Selector:     mg.Spec.ForProvider.SourceVswitchIDSelector,
		To: reference.To{
			List:    &v1alpha11.VswitchList{},
			Managed: &v1alpha11.Vswitch{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SourceVswitchID")
	}
	mg.Spec.ForProvider.SourceVswitchID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SourceVswitchIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SnatIP),
		Extract:      resource.ExtractParamPath("ip_address", false),
		Reference:    mg.Spec.InitProvider.SnatIPRef,
		Selector:     mg.Spec.InitProvider.SnatIPSelector,
		To: reference.To{
			List:    &v1alpha1.EIPAddressList{},
			Managed: &v1alpha1.EIPAddress{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SnatIP")
	}
	mg.Spec.InitProvider.SnatIP = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SnatIPRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SnatTableID),
		Extract:      resource.ExtractParamPath("snat_table_ids", true),
		Reference:    mg.Spec.InitProvider.SnatTableIDRef,
		Selector:     mg.Spec.InitProvider.SnatTableIDSelector,
		To: reference.To{
			List:    &NATGatewayList{},
			Managed: &NATGateway{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SnatTableID")
	}
	mg.Spec.InitProvider.SnatTableID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SnatTableIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourceVswitchID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.SourceVswitchIDRef,
		Selector:     mg.Spec.InitProvider.SourceVswitchIDSelector,
		To: reference.To{
			List:    &v1alpha11.VswitchList{},
			Managed: &v1alpha11.Vswitch{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SourceVswitchID")
	}
	mg.Spec.InitProvider.SourceVswitchID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SourceVswitchIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this VPCNATIP.
func (mg *VPCNATIP) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NATGatewayID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.NATGatewayIDRef,
		Selector:     mg.Spec.ForProvider.NATGatewayIDSelector,
		To: reference.To{
			List:    &NATGatewayList{},
			Managed: &NATGateway{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NATGatewayID")
	}
	mg.Spec.ForProvider.NATGatewayID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NATGatewayIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NATGatewayID),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.NATGatewayIDRef,
		Selector:     mg.Spec.InitProvider.NATGatewayIDSelector,
		To: reference.To{
			List:    &NATGatewayList{},
			Managed: &NATGateway{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NATGatewayID")
	}
	mg.Spec.InitProvider.NATGatewayID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NATGatewayIDRef = rsp.ResolvedReference

	return nil
}
