// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VPCNATIPInitParameters struct {

	// Specifies whether to only precheck the request. Valid values:
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// The ID of the Virtual Private Cloud (VPC) NAT gateway for which you want to create the NAT IP address.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/natgateway/v1alpha1.NATGateway
	NATGatewayID *string `json:"natGatewayId,omitempty" tf:"nat_gateway_id,omitempty"`

	// Reference to a NATGateway in natgateway to populate natGatewayId.
	// +kubebuilder:validation:Optional
	NATGatewayIDRef *v1.Reference `json:"natGatewayIdRef,omitempty" tf:"-"`

	// Selector for a NATGateway in natgateway to populate natGatewayId.
	// +kubebuilder:validation:Optional
	NATGatewayIDSelector *v1.Selector `json:"natGatewayIdSelector,omitempty" tf:"-"`

	// The NAT IP address to be created.
	NATIP *string `json:"natIp,omitempty" tf:"nat_ip,omitempty"`

	// The CIDR block to which the NAT IP address belongs.
	NATIPCidr *string `json:"natIpCidr,omitempty" tf:"nat_ip_cidr,omitempty"`

	// (Removed since v1.274.0) Field nat_ip_cidr_id has been removed from provider version 1.274.0.
	NATIPCidrID *string `json:"natIpCidrId,omitempty" tf:"nat_ip_cidr_id,omitempty"`

	// The description of the NAT IP address. The description must be 2 to 256 characters in length and start with a letter. The description cannot start with http:// or https://.
	NATIPDescription *string `json:"natIpDescription,omitempty" tf:"nat_ip_description,omitempty"`

	// The name of the NAT IP address. The name must be 2 to 128 characters in length, and can contain letters, digits, periods (.), underscores (_), and hyphens (-). It must start with a letter. The name must start with a letter and cannot start with http:// or https://.
	NATIPName *string `json:"natIpName,omitempty" tf:"nat_ip_name,omitempty"`
}

type VPCNATIPObservation struct {

	// Specifies whether to only precheck the request. Valid values:
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// The ID of the resource supplied above. The value is formulated as <nat_gateway_id>:<nat_ip_id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the Virtual Private Cloud (VPC) NAT gateway for which you want to create the NAT IP address.
	NATGatewayID *string `json:"natGatewayId,omitempty" tf:"nat_gateway_id,omitempty"`

	// The NAT IP address to be created.
	NATIP *string `json:"natIp,omitempty" tf:"nat_ip,omitempty"`

	// The CIDR block to which the NAT IP address belongs.
	NATIPCidr *string `json:"natIpCidr,omitempty" tf:"nat_ip_cidr,omitempty"`

	// (Removed since v1.274.0) Field nat_ip_cidr_id has been removed from provider version 1.274.0.
	NATIPCidrID *string `json:"natIpCidrId,omitempty" tf:"nat_ip_cidr_id,omitempty"`

	// The description of the NAT IP address. The description must be 2 to 256 characters in length and start with a letter. The description cannot start with http:// or https://.
	NATIPDescription *string `json:"natIpDescription,omitempty" tf:"nat_ip_description,omitempty"`

	// Ihe ID of the Nat Ip.
	NATIPID *string `json:"natIpId,omitempty" tf:"nat_ip_id,omitempty"`

	// The name of the NAT IP address. The name must be 2 to 128 characters in length, and can contain letters, digits, periods (.), underscores (_), and hyphens (-). It must start with a letter. The name must start with a letter and cannot start with http:// or https://.
	NATIPName *string `json:"natIpName,omitempty" tf:"nat_ip_name,omitempty"`

	// The status of the NAT IP address.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type VPCNATIPParameters struct {

	// Specifies whether to only precheck the request. Valid values:
	// +kubebuilder:validation:Optional
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// The ID of the Virtual Private Cloud (VPC) NAT gateway for which you want to create the NAT IP address.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/natgateway/v1alpha1.NATGateway
	// +kubebuilder:validation:Optional
	NATGatewayID *string `json:"natGatewayId,omitempty" tf:"nat_gateway_id,omitempty"`

	// Reference to a NATGateway in natgateway to populate natGatewayId.
	// +kubebuilder:validation:Optional
	NATGatewayIDRef *v1.Reference `json:"natGatewayIdRef,omitempty" tf:"-"`

	// Selector for a NATGateway in natgateway to populate natGatewayId.
	// +kubebuilder:validation:Optional
	NATGatewayIDSelector *v1.Selector `json:"natGatewayIdSelector,omitempty" tf:"-"`

	// The NAT IP address to be created.
	// +kubebuilder:validation:Optional
	NATIP *string `json:"natIp,omitempty" tf:"nat_ip,omitempty"`

	// The CIDR block to which the NAT IP address belongs.
	// +kubebuilder:validation:Optional
	NATIPCidr *string `json:"natIpCidr,omitempty" tf:"nat_ip_cidr,omitempty"`

	// (Removed since v1.274.0) Field nat_ip_cidr_id has been removed from provider version 1.274.0.
	// +kubebuilder:validation:Optional
	NATIPCidrID *string `json:"natIpCidrId,omitempty" tf:"nat_ip_cidr_id,omitempty"`

	// The description of the NAT IP address. The description must be 2 to 256 characters in length and start with a letter. The description cannot start with http:// or https://.
	// +kubebuilder:validation:Optional
	NATIPDescription *string `json:"natIpDescription,omitempty" tf:"nat_ip_description,omitempty"`

	// The name of the NAT IP address. The name must be 2 to 128 characters in length, and can contain letters, digits, periods (.), underscores (_), and hyphens (-). It must start with a letter. The name must start with a letter and cannot start with http:// or https://.
	// +kubebuilder:validation:Optional
	NATIPName *string `json:"natIpName,omitempty" tf:"nat_ip_name,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`
}

// VPCNATIPSpec defines the desired state of VPCNATIP
type VPCNATIPSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VPCNATIPParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VPCNATIPInitParameters `json:"initProvider,omitempty"`
}

// VPCNATIPStatus defines the observed state of VPCNATIP.
type VPCNATIPStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VPCNATIPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VPCNATIP is the Schema for the VPCNATIPs API. Provides a Alicloud Nat Gateway Nat Ip resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type VPCNATIP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.natIpCidr) || (has(self.initProvider) && has(self.initProvider.natIpCidr))",message="spec.forProvider.natIpCidr is a required parameter"
	Spec   VPCNATIPSpec   `json:"spec"`
	Status VPCNATIPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VPCNATIPList contains a list of VPCNATIPs
type VPCNATIPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPCNATIP `json:"items"`
}

// Repository type metadata.
var (
	VPCNATIP_Kind             = "VPCNATIP"
	VPCNATIP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VPCNATIP_Kind}.String()
	VPCNATIP_KindAPIVersion   = VPCNATIP_Kind + "." + CRDGroupVersion.String()
	VPCNATIP_GroupVersionKind = CRDGroupVersion.WithKind(VPCNATIP_Kind)
)

func init() {
	SchemeBuilder.Register(&VPCNATIP{}, &VPCNATIPList{})
}
