// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EIPInitParameters struct {

	// The EIP ID.
	ActivityID *string `json:"activityId,omitempty" tf:"activity_id,omitempty"`

	// The name of the EIP instance. This name can have a string of 2 to 128 characters, must contain only alphanumeric characters or hyphens, such as "-",".","_", and must not begin or end with a hyphen, and must not begin with http:// or https://.
	AddressName *string `json:"addressName,omitempty" tf:"address_name,omitempty"`

	// The EIP ID.
	AllocationID *string `json:"allocationId,omitempty" tf:"allocation_id,omitempty"`

	AutoPay *bool `json:"autoPay,omitempty" tf:"auto_pay,omitempty"`

	// Maximum bandwidth to the elastic public network, measured in Mbps (Mega bit per second). If this value is not specified, then automatically sets it to 5 Mbps.
	Bandwidth *string `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// Whether enable the deletion protection or not. Default value: false.
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// Description of the EIP instance, This description can have a string of 2 to 256 characters, It cannot begin with http:// or https://. Default value is null.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The EIP current status.
	HighDefinitionMonitorLogStatus *string `json:"highDefinitionMonitorLogStatus,omitempty" tf:"high_definition_monitor_log_status,omitempty"`

	// The elastic ip address
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (Depreacted, Optional, ForceNew) (It has been deprecated from version 1.126.0 and using new attribute payment_type instead) Elastic IP instance charge type. Valid values are "PrePaid" and "PostPaid". Default to "PostPaid".
	InstanceChargeType *string `json:"instanceChargeType,omitempty" tf:"instance_charge_type,omitempty"`

	// Internet charge type of the EIP, Valid values are PayByBandwidth, PayByTraffic. Default to PayByBandwidth. NOTE: From version 1.7.1 to 1.125.0, it defaults to PayByTraffic. It is only "PayByBandwidth" when instance_charge_type is PrePaid.
	InternetChargeType *string `json:"internetChargeType,omitempty" tf:"internet_charge_type,omitempty"`

	// The line type of the Elastic IP instance. Default to BGP. Other type of the isp need to open a whitelist.
	Isp *string `json:"isp,omitempty" tf:"isp,omitempty"`

	LogProject *string `json:"logProject,omitempty" tf:"log_project,omitempty"`

	LogStore *string `json:"logStore,omitempty" tf:"log_store,omitempty"`

	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (Deprecated) It has been deprecated from version 1.126.0 and using new attribute address_name instead.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Netmode *string `json:"netmode,omitempty" tf:"netmode,omitempty"`

	// The billing method of the EIP. Valid values: Subscription and PayAsYouGo. Default value is PayAsYouGo.
	PaymentType *string `json:"paymentType,omitempty" tf:"payment_type,omitempty"`

	// The duration that you will buy the resource, in month. It is valid when instance_charge_type is PrePaid. Valid values: [1-9, 12, 24, 36]. At present, the provider does not support modify "period" and you can do that via web console.
	// NOTE: The attribute period is only used to create Subscription instance or modify the PayAsYouGo instance to Subscription.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	PricingCycle *string `json:"pricingCycle,omitempty" tf:"pricing_cycle,omitempty"`

	// The EIP ID.
	PublicIPAddressPoolID *string `json:"publicIpAddressPoolId,omitempty" tf:"public_ip_address_pool_id,omitempty"`

	// The Id of resource group which the eip belongs.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	SecurityProtectionTypes []*string `json:"securityProtectionTypes,omitempty" tf:"security_protection_types,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type EIPObservation struct {

	// The EIP ID.
	ActivityID *string `json:"activityId,omitempty" tf:"activity_id,omitempty"`

	// The name of the EIP instance. This name can have a string of 2 to 128 characters, must contain only alphanumeric characters or hyphens, such as "-",".","_", and must not begin or end with a hyphen, and must not begin with http:// or https://.
	AddressName *string `json:"addressName,omitempty" tf:"address_name,omitempty"`

	// The EIP ID.
	AllocationID *string `json:"allocationId,omitempty" tf:"allocation_id,omitempty"`

	AutoPay *bool `json:"autoPay,omitempty" tf:"auto_pay,omitempty"`

	// Maximum bandwidth to the elastic public network, measured in Mbps (Mega bit per second). If this value is not specified, then automatically sets it to 5 Mbps.
	Bandwidth *string `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	// Whether enable the deletion protection or not. Default value: false.
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// Description of the EIP instance, This description can have a string of 2 to 256 characters, It cannot begin with http:// or https://. Default value is null.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The EIP current status.
	HighDefinitionMonitorLogStatus *string `json:"highDefinitionMonitorLogStatus,omitempty" tf:"high_definition_monitor_log_status,omitempty"`

	// The EIP ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The elastic ip address
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (Depreacted, Optional, ForceNew) (It has been deprecated from version 1.126.0 and using new attribute payment_type instead) Elastic IP instance charge type. Valid values are "PrePaid" and "PostPaid". Default to "PostPaid".
	InstanceChargeType *string `json:"instanceChargeType,omitempty" tf:"instance_charge_type,omitempty"`

	// Internet charge type of the EIP, Valid values are PayByBandwidth, PayByTraffic. Default to PayByBandwidth. NOTE: From version 1.7.1 to 1.125.0, it defaults to PayByTraffic. It is only "PayByBandwidth" when instance_charge_type is PrePaid.
	InternetChargeType *string `json:"internetChargeType,omitempty" tf:"internet_charge_type,omitempty"`

	// The line type of the Elastic IP instance. Default to BGP. Other type of the isp need to open a whitelist.
	Isp *string `json:"isp,omitempty" tf:"isp,omitempty"`

	LogProject *string `json:"logProject,omitempty" tf:"log_project,omitempty"`

	LogStore *string `json:"logStore,omitempty" tf:"log_store,omitempty"`

	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (Deprecated) It has been deprecated from version 1.126.0 and using new attribute address_name instead.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Netmode *string `json:"netmode,omitempty" tf:"netmode,omitempty"`

	// The billing method of the EIP. Valid values: Subscription and PayAsYouGo. Default value is PayAsYouGo.
	PaymentType *string `json:"paymentType,omitempty" tf:"payment_type,omitempty"`

	// The duration that you will buy the resource, in month. It is valid when instance_charge_type is PrePaid. Valid values: [1-9, 12, 24, 36]. At present, the provider does not support modify "period" and you can do that via web console.
	// NOTE: The attribute period is only used to create Subscription instance or modify the PayAsYouGo instance to Subscription.
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	PricingCycle *string `json:"pricingCycle,omitempty" tf:"pricing_cycle,omitempty"`

	// The EIP ID.
	PublicIPAddressPoolID *string `json:"publicIpAddressPoolId,omitempty" tf:"public_ip_address_pool_id,omitempty"`

	// The Id of resource group which the eip belongs.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	SecurityProtectionTypes []*string `json:"securityProtectionTypes,omitempty" tf:"security_protection_types,omitempty"`

	// The EIP current status.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type EIPParameters struct {

	// The EIP ID.
	// +kubebuilder:validation:Optional
	ActivityID *string `json:"activityId,omitempty" tf:"activity_id,omitempty"`

	// The name of the EIP instance. This name can have a string of 2 to 128 characters, must contain only alphanumeric characters or hyphens, such as "-",".","_", and must not begin or end with a hyphen, and must not begin with http:// or https://.
	// +kubebuilder:validation:Optional
	AddressName *string `json:"addressName,omitempty" tf:"address_name,omitempty"`

	// The EIP ID.
	// +kubebuilder:validation:Optional
	AllocationID *string `json:"allocationId,omitempty" tf:"allocation_id,omitempty"`

	// +kubebuilder:validation:Optional
	AutoPay *bool `json:"autoPay,omitempty" tf:"auto_pay,omitempty"`

	// Maximum bandwidth to the elastic public network, measured in Mbps (Mega bit per second). If this value is not specified, then automatically sets it to 5 Mbps.
	// +kubebuilder:validation:Optional
	Bandwidth *string `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// Whether enable the deletion protection or not. Default value: false.
	// +kubebuilder:validation:Optional
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// Description of the EIP instance, This description can have a string of 2 to 256 characters, It cannot begin with http:// or https://. Default value is null.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The EIP current status.
	// +kubebuilder:validation:Optional
	HighDefinitionMonitorLogStatus *string `json:"highDefinitionMonitorLogStatus,omitempty" tf:"high_definition_monitor_log_status,omitempty"`

	// The elastic ip address
	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// (Depreacted, Optional, ForceNew) (It has been deprecated from version 1.126.0 and using new attribute payment_type instead) Elastic IP instance charge type. Valid values are "PrePaid" and "PostPaid". Default to "PostPaid".
	// +kubebuilder:validation:Optional
	InstanceChargeType *string `json:"instanceChargeType,omitempty" tf:"instance_charge_type,omitempty"`

	// Internet charge type of the EIP, Valid values are PayByBandwidth, PayByTraffic. Default to PayByBandwidth. NOTE: From version 1.7.1 to 1.125.0, it defaults to PayByTraffic. It is only "PayByBandwidth" when instance_charge_type is PrePaid.
	// +kubebuilder:validation:Optional
	InternetChargeType *string `json:"internetChargeType,omitempty" tf:"internet_charge_type,omitempty"`

	// The line type of the Elastic IP instance. Default to BGP. Other type of the isp need to open a whitelist.
	// +kubebuilder:validation:Optional
	Isp *string `json:"isp,omitempty" tf:"isp,omitempty"`

	// +kubebuilder:validation:Optional
	LogProject *string `json:"logProject,omitempty" tf:"log_project,omitempty"`

	// +kubebuilder:validation:Optional
	LogStore *string `json:"logStore,omitempty" tf:"log_store,omitempty"`

	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (Deprecated) It has been deprecated from version 1.126.0 and using new attribute address_name instead.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Netmode *string `json:"netmode,omitempty" tf:"netmode,omitempty"`

	// The billing method of the EIP. Valid values: Subscription and PayAsYouGo. Default value is PayAsYouGo.
	// +kubebuilder:validation:Optional
	PaymentType *string `json:"paymentType,omitempty" tf:"payment_type,omitempty"`

	// The duration that you will buy the resource, in month. It is valid when instance_charge_type is PrePaid. Valid values: [1-9, 12, 24, 36]. At present, the provider does not support modify "period" and you can do that via web console.
	// NOTE: The attribute period is only used to create Subscription instance or modify the PayAsYouGo instance to Subscription.
	// +kubebuilder:validation:Optional
	Period *float64 `json:"period,omitempty" tf:"period,omitempty"`

	// +kubebuilder:validation:Optional
	PricingCycle *string `json:"pricingCycle,omitempty" tf:"pricing_cycle,omitempty"`

	// The EIP ID.
	// +kubebuilder:validation:Optional
	PublicIPAddressPoolID *string `json:"publicIpAddressPoolId,omitempty" tf:"public_ip_address_pool_id,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The Id of resource group which the eip belongs.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// +kubebuilder:validation:Optional
	SecurityProtectionTypes []*string `json:"securityProtectionTypes,omitempty" tf:"security_protection_types,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

// EIPSpec defines the desired state of EIP
type EIPSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EIPParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EIPInitParameters `json:"initProvider,omitempty"`
}

// EIPStatus defines the observed state of EIP.
type EIPStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EIPObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EIP is the Schema for the EIPs API. Provides a ECS EIP resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type EIP struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              EIPSpec   `json:"spec"`
	Status            EIPStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EIPList contains a list of EIPs
type EIPList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EIP `json:"items"`
}

// Repository type metadata.
var (
	EIP_Kind             = "EIP"
	EIP_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EIP_Kind}.String()
	EIP_KindAPIVersion   = EIP_Kind + "." + CRDGroupVersion.String()
	EIP_GroupVersionKind = CRDGroupVersion.WithKind(EIP_Kind)
)

func init() {
	SchemeBuilder.Register(&EIP{}, &EIPList{})
}
