apiVersion: fcv3.alibabacloud.crossplane.io/v1alpha1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: fcv3/v1alpha1/function
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    code:
    - checksumSecretRef:
        key: checksum
        name: fcv3-function-secret
        namespace: crossplane-system
      ossBucketNameSecretRef:
        key: ossBucketName
        name: fcv3-function-secret
        namespace: crossplane-system
      ossObjectNameSecretRef:
        key: ossObjectName
        name: fcv3-function-secret
        namespace: crossplane-system
#    - checksum: 4270285996107335518
##      ossBucketName: crossplane-example-for-function-20250725
##      ossObjectName: FCV3Py39.zip
#      ossBucketNameSelector:
#        matchLabels:
#          testing.upbound.io/example-name: function
#      ossObjectNameSelector:
#        matchLabels:
#          testing.upbound.io/example-name: function
    cpu: 0.5
    customRuntimeConfig:
    - args:
      - app.py
      - xx
      - x
      command:
      - python
      - -c
      - example
      healthCheckConfig:
      - failureThreshold: 3
        httpGetUrl: /ready
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      port: 9000
    description: Create
    diskSize: 512
    environmentVariables:
      EnvKey: EnvVal
    functionName: crossplane-example-function-20250725
    handler: index.handler
    instanceConcurrency: 2
    instanceLifecycleConfig:
    - initializer:
      - handler: index.init
        timeout: 1
      preStop:
      - handler: index.stop
        timeout: 1
    internetAccess: true
    layersSecretRef:
    - key: layer1
      name: fcv3-function-secret
      namespace: crossplane-system
    logConfig:
    - logBeginRule: None
    memorySize: 512
    region: cn-beijing
    runtime: custom.debian10
    timeout: 3
    vpcConfig:
    - vpcIdSelector:
        matchLabels:
          testing.upbound.io/example-name: function
      vSwitchIdSelector:
        matchLabels:
          testing.upbound.io/example-name: function
      securityGroupIdSelector:
        matchLabels:
          testing.upbound.io/example-name: function

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: fcv3/v1alpha1/function
  labels:
    testing.upbound.io/example-name: function
  name: function
spec:
  forProvider:
    bucket: crossplane-example-for-function-20250725
    region: cn-beijing

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: fcv3/v1alpha1/function
  labels:
    testing.upbound.io/example-name: function
  name: function
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: function
    content: print('hello')
    key: FCV3Py39.zip
    region: cn-beijing

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: fcv3/v1alpha1/function
  labels:
    testing.upbound.io/example-name: function
  name: function
spec:
  forProvider:
    cidrBlock: 10.0.0.0/8
    region: cn-beijing
    vpcName: crossplane-example-for-function-20250725

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: fcv3/v1alpha1/function
  labels:
    testing.upbound.io/example-name: function
  name: function
spec:
  forProvider:
    cidrBlock: 10.0.1.0/24
    zoneId: cn-beijing-f
    region: cn-beijing
    vswitchName: crossplane-example-for-function-20250725
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: function

---
apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: fcv3/v1alpha1/function
  labels:
    testing.upbound.io/example-name: function
  name: function
spec:
  forProvider:
    region: cn-beijing
    securityGroupName: crossplane-example-for-function-20250725
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: function

---
apiVersion: v1
kind: Secret
metadata:
  name: fcv3-function-secret
  namespace: crossplane-system
type: Opaque
stringData:
  checkSum: "4270285996107335518"
  ossBucketName: "crossplane-example-for-function-20250725"
  ossObjectName: "FCV3Py39.zip"
  layer1: "acs:fc:cn-beijing:official:layers/Python39-Aliyun-SDK/versions/3"
