apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Invocation
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/invocation
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    commandIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    instanceIdRefs:
    - name: default
    region: cn-beijing

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Command
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/invocation
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    commandContent: ZWNobyBoZWxsbyx7e25hbWV9fQ==
    description: For Terraform Test
    enableParameter: true
    name: ${var.name}
    region: cn-beijing
    type: RunShellScript
    workingDir: /root

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/invocation
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    imageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: alicloud_images
    instanceName: ${var.name}
    instanceType: ${data.alicloud_instance_types.default.instance_types.0.id}
    internetChargeType: PayByTraffic
    internetMaxBandwidthOut: 5
    region: cn-beijing
    securityGroupRefs:
    - name: default
    systemDiskCategory: cloud_efficiency
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/invocation
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: cn-beijing
    securityGroupName: ${var.name}
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/invocation
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrIp: 172.16.0.0/24
    ipProtocol: tcp
    nicType: intranet
    policy: accept
    portRange: 22/22
    priority: 1
    region: cn-beijing
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    type: ingress

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/invocation
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.16.0.0/16
    region: cn-beijing
    vpcName: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/invocation
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.16.0.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchName: ${var.name}
    zoneId: ${data.alicloud_zones.default.zones.0.id}
