apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroupRule
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/securitygrouprule
  labels:
    testing.upbound.io/example-name: allow_all_tcp
  name: allow-all-tcp
spec:
  forProvider:
    cidrIp: 0.0.0.0/0
    ipProtocol: tcp
    nicType: intranet
    policy: accept
    portRange: 1/65535
    priority: 1
    region: cn-beijing
    securityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    type: ingress

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/securitygrouprule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: cn-beijing
    securityGroupName: default
