//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Entry) DeepCopyInto(out *Entry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Entry.
func (in *Entry) DeepCopy() *Entry {
	if in == nil {
		return nil
	}
	out := new(Entry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Entry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntryInitParameters) DeepCopyInto(out *EntryInitParameters) {
	*out = *in
	if in.ExternalIP != nil {
		in, out := &in.ExternalIP, &out.ExternalIP
		*out = new(string)
		**out = **in
	}
	if in.ExternalIPRef != nil {
		in, out := &in.ExternalIPRef, &out.ExternalIPRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalIPSelector != nil {
		in, out := &in.ExternalIPSelector, &out.ExternalIPSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalPort != nil {
		in, out := &in.ExternalPort, &out.ExternalPort
		*out = new(string)
		**out = **in
	}
	if in.ForwardEntryName != nil {
		in, out := &in.ForwardEntryName, &out.ForwardEntryName
		*out = new(string)
		**out = **in
	}
	if in.ForwardTableID != nil {
		in, out := &in.ForwardTableID, &out.ForwardTableID
		*out = new(string)
		**out = **in
	}
	if in.ForwardTableIDRef != nil {
		in, out := &in.ForwardTableIDRef, &out.ForwardTableIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ForwardTableIDSelector != nil {
		in, out := &in.ForwardTableIDSelector, &out.ForwardTableIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.IPProtocol != nil {
		in, out := &in.IPProtocol, &out.IPProtocol
		*out = new(string)
		**out = **in
	}
	if in.InternalIP != nil {
		in, out := &in.InternalIP, &out.InternalIP
		*out = new(string)
		**out = **in
	}
	if in.InternalPort != nil {
		in, out := &in.InternalPort, &out.InternalPort
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PortBreak != nil {
		in, out := &in.PortBreak, &out.PortBreak
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntryInitParameters.
func (in *EntryInitParameters) DeepCopy() *EntryInitParameters {
	if in == nil {
		return nil
	}
	out := new(EntryInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntryList) DeepCopyInto(out *EntryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Entry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntryList.
func (in *EntryList) DeepCopy() *EntryList {
	if in == nil {
		return nil
	}
	out := new(EntryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EntryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntryObservation) DeepCopyInto(out *EntryObservation) {
	*out = *in
	if in.ExternalIP != nil {
		in, out := &in.ExternalIP, &out.ExternalIP
		*out = new(string)
		**out = **in
	}
	if in.ExternalPort != nil {
		in, out := &in.ExternalPort, &out.ExternalPort
		*out = new(string)
		**out = **in
	}
	if in.ForwardEntryID != nil {
		in, out := &in.ForwardEntryID, &out.ForwardEntryID
		*out = new(string)
		**out = **in
	}
	if in.ForwardEntryName != nil {
		in, out := &in.ForwardEntryName, &out.ForwardEntryName
		*out = new(string)
		**out = **in
	}
	if in.ForwardTableID != nil {
		in, out := &in.ForwardTableID, &out.ForwardTableID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPProtocol != nil {
		in, out := &in.IPProtocol, &out.IPProtocol
		*out = new(string)
		**out = **in
	}
	if in.InternalIP != nil {
		in, out := &in.InternalIP, &out.InternalIP
		*out = new(string)
		**out = **in
	}
	if in.InternalPort != nil {
		in, out := &in.InternalPort, &out.InternalPort
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PortBreak != nil {
		in, out := &in.PortBreak, &out.PortBreak
		*out = new(bool)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntryObservation.
func (in *EntryObservation) DeepCopy() *EntryObservation {
	if in == nil {
		return nil
	}
	out := new(EntryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntryParameters) DeepCopyInto(out *EntryParameters) {
	*out = *in
	if in.ExternalIP != nil {
		in, out := &in.ExternalIP, &out.ExternalIP
		*out = new(string)
		**out = **in
	}
	if in.ExternalIPRef != nil {
		in, out := &in.ExternalIPRef, &out.ExternalIPRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalIPSelector != nil {
		in, out := &in.ExternalIPSelector, &out.ExternalIPSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalPort != nil {
		in, out := &in.ExternalPort, &out.ExternalPort
		*out = new(string)
		**out = **in
	}
	if in.ForwardEntryName != nil {
		in, out := &in.ForwardEntryName, &out.ForwardEntryName
		*out = new(string)
		**out = **in
	}
	if in.ForwardTableID != nil {
		in, out := &in.ForwardTableID, &out.ForwardTableID
		*out = new(string)
		**out = **in
	}
	if in.ForwardTableIDRef != nil {
		in, out := &in.ForwardTableIDRef, &out.ForwardTableIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ForwardTableIDSelector != nil {
		in, out := &in.ForwardTableIDSelector, &out.ForwardTableIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.IPProtocol != nil {
		in, out := &in.IPProtocol, &out.IPProtocol
		*out = new(string)
		**out = **in
	}
	if in.InternalIP != nil {
		in, out := &in.InternalIP, &out.InternalIP
		*out = new(string)
		**out = **in
	}
	if in.InternalPort != nil {
		in, out := &in.InternalPort, &out.InternalPort
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PortBreak != nil {
		in, out := &in.PortBreak, &out.PortBreak
		*out = new(bool)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntryParameters.
func (in *EntryParameters) DeepCopy() *EntryParameters {
	if in == nil {
		return nil
	}
	out := new(EntryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntrySpec) DeepCopyInto(out *EntrySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntrySpec.
func (in *EntrySpec) DeepCopy() *EntrySpec {
	if in == nil {
		return nil
	}
	out := new(EntrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntryStatus) DeepCopyInto(out *EntryStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntryStatus.
func (in *EntryStatus) DeepCopy() *EntryStatus {
	if in == nil {
		return nil
	}
	out := new(EntryStatus)
	in.DeepCopyInto(out)
	return out
}
