// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *GatewayEndpoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GatewayEndpointRouteTableAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IPv4Gateway) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouteEntry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouteTable) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RouteTableAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VPC) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vswitch) Hub() {}
