// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RouteEntryInitParameters struct {

	// The description of the Route Entry. The description must be 1 to 256 characters in length, and cannot start with http:// or https://.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The destination CIDR block of the custom route entry.
	DestinationCidrblock *string `json:"destinationCidrblock,omitempty" tf:"destination_cidrblock,omitempty"`

	// The name of the Route Entry. The name must be 1 to 128 characters in length, and cannot start with http:// or https://.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of Next Hop.
	NexthopID *string `json:"nexthopId,omitempty" tf:"nexthop_id,omitempty"`

	// The type of Next Hop. Valid values:
	NexthopType *string `json:"nexthopType,omitempty" tf:"nexthop_type,omitempty"`

	// The ID of the Route Table.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/vpc/v1alpha1.RouteTable
	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	// Reference to a RouteTable in vpc to populate routeTableId.
	// +kubebuilder:validation:Optional
	RouteTableIDRef *v1.Reference `json:"routeTableIdRef,omitempty" tf:"-"`

	// Selector for a RouteTable in vpc to populate routeTableId.
	// +kubebuilder:validation:Optional
	RouteTableIDSelector *v1.Selector `json:"routeTableIdSelector,omitempty" tf:"-"`
}

type RouteEntryObservation struct {

	// The description of the Route Entry. The description must be 1 to 256 characters in length, and cannot start with http:// or https://.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The destination CIDR block of the custom route entry.
	DestinationCidrblock *string `json:"destinationCidrblock,omitempty" tf:"destination_cidrblock,omitempty"`

	// It formats as <route_table_id>:<router_id>:<destination_cidrblock>:<nexthop_type>:<nexthop_id>.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the Route Entry. The name must be 1 to 128 characters in length, and cannot start with http:// or https://.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of Next Hop.
	NexthopID *string `json:"nexthopId,omitempty" tf:"nexthop_id,omitempty"`

	// The type of Next Hop. Valid values:
	NexthopType *string `json:"nexthopType,omitempty" tf:"nexthop_type,omitempty"`

	// The ID of the Route Table.
	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	// (Deprecated) This argument has been deprecated. Please use other arguments to launch a custom route entry.
	RouterID *string `json:"routerId,omitempty" tf:"router_id,omitempty"`
}

type RouteEntryParameters struct {

	// The description of the Route Entry. The description must be 1 to 256 characters in length, and cannot start with http:// or https://.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The destination CIDR block of the custom route entry.
	// +kubebuilder:validation:Optional
	DestinationCidrblock *string `json:"destinationCidrblock,omitempty" tf:"destination_cidrblock,omitempty"`

	// The name of the Route Entry. The name must be 1 to 128 characters in length, and cannot start with http:// or https://.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of Next Hop.
	// +kubebuilder:validation:Optional
	NexthopID *string `json:"nexthopId,omitempty" tf:"nexthop_id,omitempty"`

	// The type of Next Hop. Valid values:
	// +kubebuilder:validation:Optional
	NexthopType *string `json:"nexthopType,omitempty" tf:"nexthop_type,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"-"`

	// The ID of the Route Table.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-alibabacloud/apis/vpc/v1alpha1.RouteTable
	// +kubebuilder:validation:Optional
	RouteTableID *string `json:"routeTableId,omitempty" tf:"route_table_id,omitempty"`

	// Reference to a RouteTable in vpc to populate routeTableId.
	// +kubebuilder:validation:Optional
	RouteTableIDRef *v1.Reference `json:"routeTableIdRef,omitempty" tf:"-"`

	// Selector for a RouteTable in vpc to populate routeTableId.
	// +kubebuilder:validation:Optional
	RouteTableIDSelector *v1.Selector `json:"routeTableIdSelector,omitempty" tf:"-"`
}

// RouteEntrySpec defines the desired state of RouteEntry
type RouteEntrySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RouteEntryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RouteEntryInitParameters `json:"initProvider,omitempty"`
}

// RouteEntryStatus defines the observed state of RouteEntry.
type RouteEntryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RouteEntryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RouteEntry is the Schema for the RouteEntrys API. Provides a Alicloud Route Entry resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type RouteEntry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RouteEntrySpec   `json:"spec"`
	Status            RouteEntryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RouteEntryList contains a list of RouteEntrys
type RouteEntryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RouteEntry `json:"items"`
}

// Repository type metadata.
var (
	RouteEntry_Kind             = "RouteEntry"
	RouteEntry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RouteEntry_Kind}.String()
	RouteEntry_KindAPIVersion   = RouteEntry_Kind + "." + CRDGroupVersion.String()
	RouteEntry_GroupVersionKind = CRDGroupVersion.WithKind(RouteEntry_Kind)
)

func init() {
	SchemeBuilder.Register(&RouteEntry{}, &RouteEntryList{})
}
