apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: RouteTableAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routetableattachment
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    region: cn-beijing
    routeTableIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: RouteTable
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routetableattachment
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    description: route_table_attachment
    region: cn-beijing
    routeTableName: ${var.name}
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routetableattachment
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    cidrBlock: 172.16.0.0/12
    region: cn-beijing
    vpcName: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/routetableattachment
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    cidrBlock: 172.16.0.0/21
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    vswitchName: ${var.name}
    zoneId: ${data.alicloud_zones.default.zones[0].id}
