apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPCPeerConnectionAccepter
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpcpeerconnectionaccepter
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    provider: ${alicloud.accepting}
    region: cn-beijing

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpcpeerconnectionaccepter
  labels:
    testing.upbound.io/example-name: accepting
  name: accepting
spec:
  forProvider:
    cidrBlock: 192.168.0.0/16
    provider: ${alicloud.accepting}
    region: cn-beijing
    vpcName: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpcpeerconnectionaccepter
  labels:
    testing.upbound.io/example-name: local
  name: local
spec:
  forProvider:
    cidrBlock: 10.4.0.0/16
    provider: ${alicloud.local}
    region: cn-beijing
    vpcName: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPCPeerConnection
metadata:
  annotations:
    meta.upbound.io/example-id: vpc/v1alpha1/vpcpeerconnectionaccepter
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    acceptingAliUid: ${data.alicloud_account.accepting.id}
    acceptingRegionId: ${var.accepting_region}
    acceptingVpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: accepting
    description: ${var.name}
    peerConnectionName: ${var.name}
    provider: ${alicloud.local}
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: local
